services:
  scrapbox:
    image: syuuzu/scrapbox:latest
    container_name: scrapbox
    volumes:
      - ./database:/app/database:rw
      - ./uploads:/app/uploads:rw
    ports:
      - '3815:3815'
    restart: always
